apiVersion: v1
kind: Service
metadata:
  name: disaster-classifier-service
spec:
  selector:
    app: disaster-classifier
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort